// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TRID.FeatureFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("AmortizationValidation", SourceFile="FeatureFiles\\AmortizationValidation.feature", SourceLine=0)]
    public partial class AmortizationValidationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AmortizationValidation.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AmortizationValidation", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage(string scenarioNo, string rowNumber, string pcSheetName, string miSheetName, string cdSheetName, string aRowNumber, string aSheetName, string eSheetName, string psSheetName, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
                    "ion page", exampleTags);
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
testRunner.Given("user is at TRID application homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.And(string.Format("user have closing disclosure data from excel sheet {0} for the scenario {1}", cdSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
 testRunner.And(string.Format("user have Mortgage Insurance data from excel sheet {0} for the scenario {1}", miSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And(string.Format("user have variable loan data from excel sheet {0} for the scenario {1}", aSheetName, aRowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And(string.Format("user have Prepaid Charges data from excel sheet {0} for the scenario {1}", pcSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And(string.Format("user have Export data from excel sheet {0} for the scenario {1}", eSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And(string.Format("user have Payment Schedule data from excel sheet {0} for the scenario {1}", psSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
testRunner.When("user navigate to Loan Inputs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And("user selects Calculation Method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("user selects loan type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("user selects Frequency of Payments", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("user selects Loan Term", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("user selects Repayment Term Type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
    testRunner.And("user enters Loan detail input values for computation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("user enters pmi rate values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.And("user enters other pmi input values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.And("user selects value for Is Ins Escrowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And("user selects value for Is Tax Escrowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And("user selects value for Is Other1 Escrowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("user selects value for Is Other2 Escrowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("user enters input values for Cushion Months", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("user enters input value for Date Of First Monthly PMI Disbursement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("user enters values for Escrow insurance Inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("user enters values for Escrow Tax Calculations Inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("user enters values for Escrow Other1 Calculations Inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("user enters values for Escrow Other2 Calculations Inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("user enters all input values for Prepaid Charges", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("user enters input value for prepaid custom fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("user navigates to Disclosure Inputs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("user enters disclosed input values for closing disclousre section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("user enters disclsoed input values for Loan Estimate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And("user enters disclosed input values for Prepaid Charges", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.And("user enters disclosed input values for Escrow Property", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("user navigates to Amortization Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
testRunner.Then("updated/computed Payment Stream Number value should display on Payment Schedule G" +
                    "rid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 42
 testRunner.And("updated/computed Number of Payments value should display on Payment Schedule Grid" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.And("updated/computed Payment Amount value should display on Payment Schedule Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.And("updated/computed Monthly Payment value should display on Payment Schedule Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.And("updated/computed Monthly PMI value should display on Payment Schedule Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("updated/computed Ins Escrowed Amount value should display on Payment Schedule Gri" +
                    "d", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.And("updated/computed Tax Escrowed Amount value should display on Payment Schedule Gri" +
                    "d", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 001", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_001()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("001", "2", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 002", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_002()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("002", "3", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 003", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_003()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("003", "4", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 004", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_004()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("004", "5", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 006", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_006()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("006", "6", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 007", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_007()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("007", "7", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 008", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_008()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("008", "8", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 009", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_009()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("009", "9", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 011", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_011()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("011", "10", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 012", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_012()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("012", "11", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 013", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_013()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("013", "12", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 014", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_014()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("014", "13", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 016", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_016()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("016", "14", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 017", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_017()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("017", "15", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 019", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_019()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("019", "16", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 036", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_036()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("036", "17", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "2", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 037", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_037()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("037", "18", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "3", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 038", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_038()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("038", "19", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "4", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 039", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_039()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("039", "20", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "5", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 040", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_040()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("040", "21", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 041", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_041()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("041", "22", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 042", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_042()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("042", "23", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 043", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_043()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("043", "24", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 044", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_044()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("044", "25", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 050", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_050()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("050", "28", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 051", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_051()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("051", "29", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 052", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_052()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("052", "30", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 053", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_053()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("053", "31", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 054", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_054()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("054", "32", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 055", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_055()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("055", "33", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 056", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_056()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("056", "34", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 057", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_057()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("057", "35", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 070", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_070()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("070", "46", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 071", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_071()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("071", "47", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 072", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_072()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("072", "48", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 073", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_073()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("073", "49", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 074", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_074()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("074", "50", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 075", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_075()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("075", "51", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 076", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_076()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("076", "52", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 077", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_077()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("077", "53", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 090", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_090()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("090", "64", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 091", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_091()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("091", "65", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 092", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_092()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("092", "66", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 093", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_093()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("093", "67", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 094", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_094()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("094", "68", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 095", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_095()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("095", "69", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 096", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_096()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("096", "70", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 097", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_097()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("097", "71", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 110", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_110()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("110", "82", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 111", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_111()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("111", "83", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 112", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_112()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("112", "84", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 113", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_113()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("113", "85", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 114", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_114()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("114", "86", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 115", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_115()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("115", "87", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 116", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_116()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("116", "88", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating Payment Schedule values on Amortizat" +
            "ion page, 117", SourceLine=49)]
        public virtual void GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage_117()
        {
            this.GivingInputsFromExcelFileAndValidatingPaymentScheduleValuesOnAmortizationPage("117", "89", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", "Export", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage(string scenarioNo, string rowNumber, string psSheetName, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Uploading JSON file and validating Payment Schedule values on Amortization page", exampleTags);
#line 108
this.ScenarioSetup(scenarioInfo);
#line 109
testRunner.Given("user is at TRID application homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 110
 testRunner.And(string.Format("user have Payment Schedule data from excel sheet {0} for the scenario {1}", psSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
testRunner.When("user upload json file for the scenario", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 112
 testRunner.And("user navigates to Amortization Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
testRunner.Then("updated/computed Payment Stream Number value should display on Payment Schedule G" +
                    "rid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 114
 testRunner.And("updated/computed Number of Payments value should display on Payment Schedule Grid" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.And("updated/computed Payment Amount value should display on Payment Schedule Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.And("updated/computed Monthly Payment value should display on Payment Schedule Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.And("updated/computed Monthly PMI value should display on Payment Schedule Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
 testRunner.And("updated/computed Ins Escrowed Amount value should display on Payment Schedule Gri" +
                    "d", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
 testRunner.And("updated/computed Tax Escrowed Amount value should display on Payment Schedule Gri" +
                    "d", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "001", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_001()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("001", "2", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "002", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_002()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("002", "3", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "003", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_003()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("003", "4", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "004", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_004()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("004", "5", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "006", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_006()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("006", "6", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "007", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_007()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("007", "7", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "008", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_008()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("008", "8", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "009", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_009()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("009", "9", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "011", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_011()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("011", "10", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "012", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_012()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("012", "11", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "013", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_013()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("013", "12", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "014", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_014()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("014", "13", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "016", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_016()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("016", "14", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "017", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_017()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("017", "15", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "019", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_019()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("019", "16", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "036", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_036()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("036", "17", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "037", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_037()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("037", "18", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "038", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_038()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("038", "19", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "039", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_039()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("039", "20", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "040", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_040()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("040", "21", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "041", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_041()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("041", "22", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "042", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_042()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("042", "23", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "043", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_043()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("043", "24", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "044", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_044()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("044", "25", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "050", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_050()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("050", "28", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "051", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_051()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("051", "29", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "052", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_052()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("052", "30", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "053", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_053()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("053", "31", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "054", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_054()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("054", "32", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "055", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_055()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("055", "33", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "056", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_056()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("056", "34", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "057", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_057()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("057", "35", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "070", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_070()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("070", "46", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "071", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_071()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("071", "47", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "072", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_072()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("072", "48", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "073", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_073()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("073", "49", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "074", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_074()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("074", "50", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "075", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_075()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("075", "51", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "076", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_076()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("076", "52", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "077", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_077()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("077", "53", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "090", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_090()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("090", "64", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "091", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_091()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("091", "65", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "092", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_092()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("092", "66", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "093", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_093()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("093", "67", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "094", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_094()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("094", "68", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "095", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_095()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("095", "69", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "096", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_096()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("096", "70", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "097", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_097()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("097", "71", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "110", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_110()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("110", "82", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "111", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_111()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("111", "83", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "112", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_112()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("112", "84", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "113", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_113()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("113", "85", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "114", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_114()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("114", "86", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "115", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_115()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("115", "87", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "116", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_116()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("116", "88", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and validating Payment Schedule values on Amortization page, " +
            "117", SourceLine=121)]
        public virtual void UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage_117()
        {
            this.UploadingJSONFileAndValidatingPaymentScheduleValuesOnAmortizationPage("117", "89", "PaymentSchedule", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
