// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TRID.FeatureFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CardsValidation", SourceFile="FeatureFiles\\CardsValidation.feature", SourceLine=0)]
    public partial class CardsValidationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CardsValidation.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CardsValidation", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ValidatingCardsValueOnClosingDisclosurePage(string scenarioNo, string rowNumber, string pcSheetName, string miSheetName, string cdSheetName, string aRowNumber, string aSheetName, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validating cards value on Closing Disclosure page", exampleTags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
testRunner.Given("user is at TRID application homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.And(string.Format("user have closing disclosure data from excel sheet {0} for the scenario {1}", cdSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And(string.Format("user have Mortgage Insurance data from excel sheet {0} for the scenario {1}", miSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And(string.Format("user have variable loan data from excel sheet {0} for the scenario {1}", aSheetName, aRowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And(string.Format("user have Prepaid Charges data from excel sheet {0} for the scenario {1}", pcSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
testRunner.When("user navigate to Loan Inputs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.And("user selects Calculation Method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("user selects loan type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("user selects Frequency of Payments", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("user selects Loan Term", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("user selects Repayment Term Type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
    testRunner.And("Enter Loan detail input values for computation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
    testRunner.And("user navigate to Amortization Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
    testRunner.And("user navigate to Loan Inputs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.And("user enters pmi rate values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.And("user enters other pmi input values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And("user selects value for Is Ins Escrowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And("user selects value for Is Tax Escrowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("user selects value for Is PMI Escrowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("user enters values for Cushion Months for Insurance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("user enters values for Cushion Months for Tax", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("user enters values for Escrow insurance Inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("user enters values for Escrow Tax Calculations Inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("user enters all input values for Prepaid Charges", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("user navigates to Disclosure Inputs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("user enters disclosed input values for closing disclousre section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("user enters disclsoed input values for Loan Estimate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("user enters disclosed input values for Prepaid Charges", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("user enters disclosed input values for Escrow Property", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And("user navigates to Closing Disclosure Cards Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
testRunner.Then("updated/computed Principal and Interest value should display on Closing Disclosur" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 37
 testRunner.And("updated/computed pmi value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("updated/computed Drop off years for PMI value should display on Closing Disclosur" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("updated/computed Total Period Payment value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("updated/computed Prepaid Charges value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("updated/computed Amount Financed value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.And("updated/computed APR value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.And("updated/computed Balloon Amount value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.And("updated/computed Total of Payments value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("updated/computed Finance Charge value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.And("updated/computed TIP value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 1R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_1R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("1R", "2", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 2R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_2R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("2R", "3", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 3R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_3R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("3R", "4", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 4R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_4R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("4R", "5", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 6R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_6R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("6R", "6", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 7R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_7R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("7R", "7", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 8R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_8R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("8R", "8", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 9R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_9R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("9R", "9", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 11R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_11R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("11R", "10", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 12R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_12R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("12R", "11", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 13R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_13R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("13R", "12", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 14R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_14R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("14R", "13", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 16R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_16R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("16R", "14", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 17R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_17R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("17R", "15", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 19R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_19R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("19R", "16", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 36R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_36R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("36R", "17", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "2", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 37R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_37R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("37R", "18", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "3", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 38R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_38R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("38R", "19", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "4", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 38.1R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_38_1R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("38.1R", "20", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "5", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 39R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_39R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("39R", "21", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 40R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_40R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("40R", "22", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 41R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_41R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("41R", "23", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 42R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_42R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("42R", "24", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 43R", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_43R()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("43R", "25", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 50", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_50()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("50", "28", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 51", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_51()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("51", "29", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 52", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_52()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("52", "30", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 53", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_53()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("53", "31", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 54", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_54()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("54", "32", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 55", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_55()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("55", "33", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 56", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_56()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("56", "34", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 57", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_57()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("57", "35", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 70", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_70()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("70", "46", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 71", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_71()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("71", "47", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 72", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_72()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("72", "48", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 73", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_73()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("73", "49", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 74", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_74()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("74", "50", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 75", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_75()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("75", "51", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 76", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_76()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("76", "52", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 77", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_77()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("77", "53", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 90", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_90()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("90", "64", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 91", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_91()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("91", "65", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 92", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_92()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("92", "66", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 93", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_93()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("93", "67", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 94", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_94()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("94", "68", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 95", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_95()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("95", "69", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 96", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_96()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("96", "70", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 97", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_97()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("97", "71", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 110", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_110()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("110", "82", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 111", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_111()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("111", "83", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 112", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_112()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("112", "84", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 113", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_113()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("113", "85", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 114", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_114()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("114", "86", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 115", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_115()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("115", "87", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 116", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_116()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("116", "88", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Closing Disclosure page, 117", SourceLine=52)]
        public virtual void ValidatingCardsValueOnClosingDisclosurePage_117()
        {
            this.ValidatingCardsValueOnClosingDisclosurePage("117", "89", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        public virtual void ValidatingCardsValueOnLoanEstimatePage(string scenarioNo, string rowNumber, string pcSheetName, string miSheetName, string cdSheetName, string aRowNumber, string aSheetName, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validating cards value on Loan Estimate page", exampleTags);
#line 112
this.ScenarioSetup(scenarioInfo);
#line 113
testRunner.Given("user is at TRID application homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 114
 testRunner.And(string.Format("user have closing disclosure data from excel sheet {0} for the scenario {1}", cdSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.And(string.Format("user have Mortgage Insurance data from excel sheet {0} for the scenario {1}", miSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.And(string.Format("user have variable loan data from excel sheet {0} for the scenario {1}", aSheetName, aRowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.And(string.Format("user have Prepaid Charges data from excel sheet {0} for the scenario {1}", pcSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
testRunner.When("user navigate to Loan Inputs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 119
 testRunner.And("user selects Calculation Method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.And("user selects loan type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 121
 testRunner.And("user selects Frequency of Payments", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
 testRunner.And("user selects Loan Term", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.And("user selects Repayment Term Type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 124
    testRunner.And("Enter Loan detail input values for computation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
    testRunner.And("user navigate to Amortization Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
    testRunner.And("user navigate to Loan Inputs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 127
 testRunner.And("user enters pmi rate values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 128
 testRunner.And("user enters other pmi input values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 129
 testRunner.And("user selects value for Is Ins Escrowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.And("user selects value for Is Tax Escrowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
 testRunner.And("user selects value for Is PMI Escrowed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
 testRunner.And("user enters values for Cushion Months for Insurance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 133
 testRunner.And("user enters values for Cushion Months for Tax", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 134
 testRunner.And("user enters values for Escrow insurance Inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 135
 testRunner.And("user enters values for Escrow Tax Calculations Inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 136
 testRunner.And("user enters all input values for Prepaid Charges", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 138
 testRunner.And("user navigates to Disclosure Inputs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
 testRunner.And("user enters disclosed input values for closing disclousre section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 140
 testRunner.And("user enters disclsoed input values for Loan Estimate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
 testRunner.And("user enters disclosed input values for Prepaid Charges", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
 testRunner.And("user enters disclosed input values for Escrow Property", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
 testRunner.And("user navigates to Loan Estimate Cards Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
testRunner.Then("updated/computed in 5 Years value should display on Loan Estimate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 145
 testRunner.And("updated/computed in 5 Years principal value should display on Loan Estimate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 1R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_1R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("1R", "2", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 2R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_2R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("2R", "3", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 3R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_3R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("3R", "4", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 4R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_4R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("4R", "5", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 6R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_6R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("6R", "6", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 7R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_7R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("7R", "7", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 8R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_8R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("8R", "8", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 9R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_9R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("9R", "9", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 11R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_11R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("11R", "10", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 12R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_12R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("12R", "11", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 13R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_13R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("13R", "12", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 14R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_14R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("14R", "13", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 16R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_16R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("16R", "14", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 17R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_17R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("17R", "15", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 19R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_19R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("19R", "16", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 36R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_36R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("36R", "17", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "2", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 37R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_37R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("37R", "18", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "3", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 38R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_38R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("38R", "19", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "4", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 38.1R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_38_1R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("38.1R", "20", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "5", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 39R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_39R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("39R", "21", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 40R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_40R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("40R", "22", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 41R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_41R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("41R", "23", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 42R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_42R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("42R", "24", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 43R", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_43R()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("43R", "25", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 50", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_50()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("50", "28", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 51", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_51()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("51", "29", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 52", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_52()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("52", "30", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 53", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_53()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("53", "31", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 54", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_54()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("54", "32", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 55", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_55()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("55", "33", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 56", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_56()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("56", "34", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 57", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_57()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("57", "35", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 70", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_70()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("70", "46", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 71", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_71()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("71", "47", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 72", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_72()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("72", "48", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 73", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_73()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("73", "49", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 74", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_74()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("74", "50", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 75", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_75()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("75", "51", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 76", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_76()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("76", "52", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 77", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_77()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("77", "53", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 90", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_90()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("90", "64", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 91", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_91()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("91", "65", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 92", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_92()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("92", "66", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 93", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_93()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("93", "67", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 94", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_94()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("94", "68", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 95", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_95()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("95", "69", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 96", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_96()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("96", "70", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 97", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_97()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("97", "71", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 110", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_110()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("110", "82", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 111", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_111()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("111", "83", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 112", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_112()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("112", "84", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 113", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_113()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("113", "85", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 114", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_114()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("114", "86", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 115", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_115()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("115", "87", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 116", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_116()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("116", "88", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Validating cards value on Loan Estimate page, 117", SourceLine=147)]
        public virtual void ValidatingCardsValueOnLoanEstimatePage_117()
        {
            this.ValidatingCardsValueOnLoanEstimatePage("117", "89", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARM Terms", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
